---
# do not stop after boot failed
- lineinfile: 'dest=/etc/default/grub line=GRUB_RECORDFAIL_TIMEOUT=5'
  notify: update-grub
  tags: grub
# reduce getty
- lineinfile:
    dest: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX 4"'
  notify: update-grub
  tags: grub
